# permissions for end users to edit webpages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-editor-role
rules:
- apiGroups:
  - sandbox.rvmiller.com
  resources:
  - webpages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.rvmiller.com
  resources:
  - webpages/status
  verbs:
  - get
